# Generated by Django 5.1.15 on 2026-10-06 07:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0003_quotation_rentalcontract_dispatchreturn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('invoice_no', models.CharField(help_text='Unique commercial tax invoice identifier (e.g., INV-2026-0001).', max_length=50, primary_key=True, serialize=False, verbose_name='Invoice Number')),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, help_text='Official issuance date of this invoice.', verbose_name='Invoice Issue Date')),
                ('due_date', models.DateField(help_text='Statutory or contractually agreed payment deadline.', verbose_name='Payment Due Date')),
                ('billing_period_start', models.DateField(help_text='Start date of the operational period covered by this bill.', verbose_name='Billing Period Start')),
                ('billing_period_end', models.DateField(help_text='End date of the operational period covered by this bill.', verbose_name='Billing Period End')),
                ('rental_subtotal', models.DecimalField(decimal_places=2, help_text='Base machinery rental tariff for the billed duration.', max_digits=12, verbose_name='Base Rental Subtotal (LKR)')),
                ('excess_hours_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Supplemental tariff for operating hours exceeding contractual allowance.', max_digits=10, verbose_name='Excess Hours Charge (LKR)')),
                ('damage_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Assessed maintenance, damage, or cleaning penalties from demobilization inspection.', max_digits=10, verbose_name='Damage & Repair Charges (LKR)')),
                ('transport_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Mobilization / demobilization low-bed transport charges.', max_digits=10, verbose_name='Transport & Logistics Charges (LKR)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Statutory Value Added Tax and corporate tax levies.', max_digits=10, verbose_name='Applicable Taxes (VAT/SSCL) (LKR)')),
                ('deposit_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Portion of security deposit offset against this invoice.', max_digits=10, verbose_name='Security Deposit Deducted (LKR)')),
                ('net_total_payable', models.DecimalField(decimal_places=2, help_text='Final settlement amount payable by customer after tax and deposit offset.', max_digits=12, verbose_name='Net Total Payable (LKR)')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative settled amount paid towards this invoice.', max_digits=12, verbose_name='Paid Amount (LKR)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='UNPAID', help_text='Settlement lifecycle status.', max_length=30, verbose_name='Invoice Status')),
                ('invoice_pdf', models.FileField(blank=True, help_text='Official A4 Tax Invoice document.', null=True, upload_to='invoices/', verbose_name='Generated Invoice PDF')),
                ('contract', models.ForeignKey(help_text='Associated binding rental contract.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='rentals.rentalcontract', verbose_name='Rental Contract')),
                ('customer', models.ForeignKey(help_text='Billed customer organization.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='rentals.customer', verbose_name='Customer Organization')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('payment_id', models.CharField(help_text='Unique payment transaction identifier (e.g., PAY-2026-0001).', max_length=50, primary_key=True, serialize=False, verbose_name='Payment ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Financial transaction amount in Sri Lankan Rupees.', max_digits=12, verbose_name='Transaction Amount (LKR)')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, help_text='Date transaction was executed or credited.', verbose_name='Payment Date')),
                ('payment_type', models.CharField(choices=[('RENTAL_PAYMENT', 'Rental Invoice Payment'), ('SECURITY_DEPOSIT', 'Security Deposit Receipt'), ('DEPOSIT_REFUND', 'Security Deposit Refund')], default='RENTAL_PAYMENT', help_text='Commercial purpose of the transaction.', max_length=30, verbose_name='Payment Type')),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer / Wire'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash'), ('CARD', 'Credit / Debit Card')], help_text='Financial channel used for settlement.', max_length=30, verbose_name='Payment Method')),
                ('reference_number', models.CharField(blank=True, help_text='Bank reference number, cheque number, or transaction hash.', max_length=100, verbose_name='Reference / Cheque Number')),
                ('receipt_pdf', models.FileField(blank=True, help_text='Official electronic payment receipt.', null=True, upload_to='receipts/', verbose_name='Payment Receipt PDF')),
                ('notes', models.TextField(blank=True, help_text='Optional accounting annotations or bank details.', verbose_name='Payment Notes')),
                ('customer', models.ForeignKey(help_text='Customer organization issuing or receiving funds.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='rentals.customer', verbose_name='Customer')),
                ('invoice', models.ForeignKey(blank=True, help_text='Commercial invoice associated with this payment transaction.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.invoice', verbose_name='Settled Invoice')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Finance/Accounts officer who posted this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityDeposit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('deposit_id', models.CharField(help_text='Unique security deposit identifier (e.g., DEP-2026-0001).', max_length=50, primary_key=True, serialize=False, verbose_name='Deposit ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, help_text='Contractual security deposit escrow amount.', max_digits=12, verbose_name='Total Deposit Required/Agreed (LKR)')),
                ('received_date', models.DateField(blank=True, help_text='Date the cash deposit was received into escrow.', null=True, verbose_name='Received Date')),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative deposit amount returned to the customer.', max_digits=12, verbose_name='Refunded Amount (LKR)')),
                ('deducted_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative deposit amount retained for damage, excess hours, or invoice settlement.', max_digits=12, verbose_name='Deducted Amount (LKR)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Receipt'), ('HELD', 'Held in Escrow'), ('DEDUCTED', 'Partially / Fully Deducted'), ('REFUNDED', 'Fully Refunded')], db_index=True, default='PENDING', help_text='Current escrow status of the security deposit.', max_length=30, verbose_name='Deposit Status')),
                ('contract', models.OneToOneField(help_text='Binding rental contract covered by this security deposit.', on_delete=django.db.models.deletion.PROTECT, related_name='security_deposit_record', to='rentals.rentalcontract', verbose_name='Rental Contract')),
                ('customer', models.ForeignKey(help_text='Customer organization remitting the deposit.', on_delete=django.db.models.deletion.PROTECT, related_name='security_deposits', to='rentals.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Security Deposit',
                'verbose_name_plural': 'Security Deposits',
                'ordering': ['-created_at'],
            },
        ),
    ]
