# Generated by Django 5.1.15 on 2026-10-05 08:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('customer_code', models.CharField(help_text='Unique identifier (e.g., CUST-2026-001).', max_length=50, primary_key=True, serialize=False, verbose_name='Customer Code')),
                ('company_name', models.CharField(help_text='Registered corporate enterprise or contractor name.', max_length=200, verbose_name='Company / Corporate Name')),
                ('contact_person', models.CharField(help_text='Full name of primary commercial representative or site manager.', max_length=150, verbose_name='Primary Contact Person')),
                ('phone', models.CharField(help_text='Primary corporate or direct mobile number.', max_length=20, verbose_name='Contact Phone')),
                ('email', models.EmailField(help_text='Official email for sending quotations, contracts, and invoices.', max_length=254, verbose_name='Billing Email')),
                ('billing_address', models.TextField(help_text='Official registered corporate billing address.', verbose_name='Billing Address')),
                ('vat_tax_number', models.CharField(blank=True, help_text='Government tax registration or VAT number (if registered).', max_length=50, verbose_name='VAT / Tax Identification No.')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum approved outstanding receivables credit limit in LKR.', max_digits=12, verbose_name='Credit Limit (LKR)')),
                ('current_outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current cumulative unpaid receivables balance.', max_digits=12, verbose_name='Outstanding Balance (LKR)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked / Credit Hold'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', help_text='Commercial account standing.', max_length=20, verbose_name='Account Status')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('project_code', models.CharField(help_text='Unique identifier (e.g., PRJ-COL-001).', max_length=50, primary_key=True, serialize=False, verbose_name='Project Code')),
                ('project_name', models.CharField(help_text='Name of the construction or engineering site.', max_length=200, verbose_name='Project Name')),
                ('site_address', models.TextField(help_text='Physical delivery destination address for equipment mobilization.', verbose_name='Site Physical Address')),
                ('gps_coordinates', models.CharField(blank=True, help_text='Geographic coordinates (e.g., 6.9271,79.8612) for logistics navigation.', max_length=100, verbose_name='GPS Coordinates (Lat, Long)')),
                ('site_contact_person', models.CharField(blank=True, help_text='Resident engineer or site supervisor receiving machinery.', max_length=150, verbose_name='On-Site Contact Person')),
                ('site_contact_phone', models.CharField(blank=True, help_text='Direct phone number of on-site contact person.', max_length=20, verbose_name='On-Site Contact Phone')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Site'), ('COMPLETED', 'Completed / Handed Over')], db_index=True, default='ACTIVE', help_text='Operational status of the construction project.', max_length=20, verbose_name='Site Status')),
                ('customer', models.ForeignKey(help_text='Customer company operating this construction project.', on_delete=django.db.models.deletion.PROTECT, related_name='project_sites', to='rentals.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Project Site',
                'verbose_name_plural': 'Project Sites',
                'ordering': ['project_name'],
            },
        ),
    ]
