# Generated by Django 5.1.15 on 2026-10-05 18:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='billing_address',
            field=models.TextField(help_text='Official registered corporate or residential billing address.', verbose_name='Billing Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(help_text='Registered legal business name or individual client name.', max_length=200, verbose_name='Company / Entity Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(help_text='Designated point of contact representative.', max_length=150, verbose_name='Primary Contact Person'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Approved maximum outstanding credit ceiling before requiring managerial approval.', max_digits=12, verbose_name='Credit Limit (LKR)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current cumulative unpaid invoice amount across active and completed rentals.', max_digits=12, verbose_name='Current Outstanding Balance (LKR)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(help_text='Unique customer identifier (e.g., CUST-2026-001).', max_length=50, primary_key=True, serialize=False, verbose_name='Customer Code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(help_text='Email address for quotations, contracts, invoices, and payment receipts.', max_length=254, verbose_name='Billing & Notification Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='Primary telephone or mobile number.', max_length=20, verbose_name='Primary Phone Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', help_text='Operational standing governing quotation and rental eligibility.', max_length=20, verbose_name='Account Status'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vat_tax_number',
            field=models.CharField(blank=True, help_text='Government registered tax identification number (if applicable).', max_length=50, verbose_name='VAT / Tax Identification Number'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='customer',
            field=models.ForeignKey(help_text='Customer organization responsible for this project site.', on_delete=django.db.models.deletion.PROTECT, related_name='project_sites', to='rentals.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='gps_coordinates',
            field=models.CharField(blank=True, help_text='Geographic coordinates (e.g., 6.9271,79.8612) for dispatch mapping.', max_length=100, verbose_name='GPS Coordinates'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='project_code',
            field=models.CharField(help_text='Unique project identifier (e.g., PRJ-COL-001).', max_length=50, primary_key=True, serialize=False, verbose_name='Project Site Code'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='project_name',
            field=models.CharField(help_text='Descriptive project name (e.g., Central Expressway Section III).', max_length=200, verbose_name='Project / Site Name'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='site_address',
            field=models.TextField(help_text='Full physical site location and delivery dispatch coordinates.', verbose_name='Physical Site Address'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='site_contact_person',
            field=models.CharField(blank=True, help_text='On-site engineer, supervisor, or receiving coordinator.', max_length=150, verbose_name='On-Site Contact Person'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='site_contact_phone',
            field=models.CharField(blank=True, help_text='Direct phone contact for site dispatch and equipment handover.', max_length=20, verbose_name='On-Site Contact Phone'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], db_index=True, default='ACTIVE', help_text='Operational status of this construction project site.', max_length=20, verbose_name='Site Status'),
        ),
    ]
