# Generated by Django 5.1.15 on 2026-10-05 18:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('rentals', '0002_alter_customer_billing_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('quotation_no', models.CharField(help_text='Unique identifier (e.g., QT-2026-0001).', max_length=50, primary_key=True, serialize=False, verbose_name='Quotation Number')),
                ('start_date', models.DateField(help_text='Commencement date of prospective rental.', verbose_name='Rental Start Date')),
                ('end_date', models.DateField(help_text='Estimated completion/return date of rental.', verbose_name='Rental End Date')),
                ('rate_applied', models.DecimalField(decimal_places=2, help_text='Unit rental rate agreed for this quotation.', max_digits=10, verbose_name='Applied Rate (LKR)')),
                ('rate_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', help_text='Rate frequency tier (Daily, Weekly, Monthly).', max_length=20, verbose_name='Rate Type')),
                ('estimated_transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated mobilization and demobilization transport fee.', max_digits=10, verbose_name='Estimated Transport Cost (LKR)')),
                ('security_deposit_required', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Refundable cash deposit or escrow required before machine handover.', max_digits=10, verbose_name='Security Deposit Required (LKR)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Approved commercial discount percentage (0-100%).', max_digits=5, verbose_name='Discount Percentage (%)')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, help_text='Base rental charge before tax and transport.', max_digits=12, verbose_name='Subtotal Amount (LKR)')),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Applicable statutory taxes (e.g., VAT, SSCL).', max_digits=12, verbose_name='Total Tax Amount (LKR)')),
                ('grand_total_amount', models.DecimalField(decimal_places=2, help_text='Total quotation value including rental, transport, and taxes.', max_digits=12, verbose_name='Grand Total Amount (LKR)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_INTERNAL_APPROVAL', 'Pending Internal Approval'), ('APPROVED_BY_MANAGEMENT', 'Approved by Management'), ('SENT_TO_CUSTOMER', 'Sent to Customer'), ('ACCEPTED', 'Accepted by Customer'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CONVERTED', 'Converted to Contract')], db_index=True, default='DRAFT', help_text='Commercial lifecycle status of this quotation.', max_length=30, verbose_name='Quotation Status')),
                ('approval_date', models.DateTimeField(blank=True, help_text='Timestamp when managerial authorization was granted.', null=True, verbose_name='Approval Date & Time')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Management user who reviewed and authorized this quotation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quotations', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('customer', models.ForeignKey(help_text='Customer organization requesting the machinery quotation.', on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='rentals.customer', verbose_name='Customer')),
                ('equipment', models.ForeignKey(help_text='Machinery asset requested for rental.', on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='fleet.equipment', verbose_name='Equipment Asset')),
                ('project_site', models.ForeignKey(help_text='Designated construction site for equipment delivery.', on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='rentals.projectsite', verbose_name='Project Site')),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('contract_no', models.CharField(help_text='Unique legal contract identifier (e.g., CNT-2026-0001).', max_length=50, primary_key=True, serialize=False, verbose_name='Contract Number')),
                ('contract_start_date', models.DateField(help_text='Official start date of the rental period.', verbose_name='Contract Start Date')),
                ('contract_end_date', models.DateField(help_text='Agreed contractual completion / return date.', verbose_name='Contract End Date')),
                ('billing_cycle', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('ON_RETURN', 'On Return')], default='MONTHLY', help_text='Periodic invoice schedule (Weekly, Monthly, On Return).', max_length=20, verbose_name='Billing Cycle')),
                ('agreed_rate', models.DecimalField(decimal_places=2, help_text='Final agreed rental rate per period.', max_digits=10, verbose_name='Agreed Rate (LKR)')),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual security deposit amount collected and held in escrow.', max_digits=10, verbose_name='Deposit Paid (LKR)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISPATCHED', 'Dispatched / In Transit'), ('ON_RENT', 'On Rent'), ('PENDING_RETURN', 'Pending Return'), ('RETURNED', 'Returned'), ('CLOSED', 'Closed & Invoiced'), ('TERMINATED', 'Terminated Early')], db_index=True, default='ACTIVE', help_text='Operational and billing state of the rental contract.', max_length=20, verbose_name='Contract Status')),
                ('signed_contract_pdf', models.FileField(blank=True, help_text='Scanned or digital copy of the countersigned rental contract.', null=True, upload_to='contracts/signed_pdfs/', verbose_name='Signed Contract PDF')),
                ('customer', models.ForeignKey(help_text='Contracting customer organization.', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='rentals.customer', verbose_name='Customer')),
                ('equipment', models.ForeignKey(help_text='Machinery asset contracted for rental.', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='fleet.equipment', verbose_name='Equipment Asset')),
                ('project_site', models.ForeignKey(help_text='Designated construction site location for machine deployment.', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='rentals.projectsite', verbose_name='Project Site')),
                ('quotation', models.OneToOneField(help_text='Accepted commercial quotation converted into this binding contract.', on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='rentals.quotation', verbose_name='Originating Quotation')),
            ],
            options={
                'verbose_name': 'Rental Contract',
                'verbose_name_plural': 'Rental Contracts',
                'ordering': ['-contract_start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchReturn',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('transaction_id', models.CharField(help_text='Unique logistics transaction identifier (e.g., TRX-2026-0001).', max_length=50, primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('dispatch_datetime', models.DateTimeField(help_text='Exact date and time machinery exited depot for mobilization.', verbose_name='Dispatch Date & Time')),
                ('dispatch_hour_meter', models.DecimalField(decimal_places=2, help_text='Operating cumulative hour meter at time of mobilization.', max_digits=10, verbose_name='Dispatch Hour Meter (hrs)')),
                ('dispatch_fuel_level', models.DecimalField(decimal_places=2, help_text='Opening fuel tank level (Percentage 0-100%).', max_digits=5, verbose_name='Dispatch Fuel Level (%)')),
                ('dispatch_checklist', models.JSONField(blank=True, default=dict, help_text='Structured pre-delivery condition checklist (Tires, Hydraulic, Engine, Cabin).', verbose_name='Dispatch Inspection Checklist')),
                ('return_datetime', models.DateTimeField(blank=True, help_text='Date and time machinery was received back at the depot.', null=True, verbose_name='Return Date & Time')),
                ('return_hour_meter', models.DecimalField(blank=True, decimal_places=2, help_text='Closing cumulative hour meter upon check-in.', max_digits=10, null=True, verbose_name='Return Hour Meter (hrs)')),
                ('return_fuel_level', models.DecimalField(blank=True, decimal_places=2, help_text='Closing fuel tank level upon return.', max_digits=5, null=True, verbose_name='Return Fuel Level (%)')),
                ('return_checklist', models.JSONField(blank=True, default=dict, help_text='Structured return condition checklist.', verbose_name='Return Inspection Checklist')),
                ('damage_reported', models.BooleanField(default=False, help_text='Flag indicating whether physical damage or breakdown occurred on-site.', verbose_name='Damage / Defects Reported')),
                ('damage_notes', models.TextField(blank=True, help_text='Detailed notes on identified damages, component replacements, or repair estimates.', verbose_name='Damage Description & Assessment Notes')),
                ('excess_hours_calculated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Billable operating hours exceeding the contractual standard allowance.', max_digits=8, verbose_name='Calculated Excess Operating Hours (hrs)')),
                ('dispatch_officer', models.ForeignKey(help_text='Operations or Yard officer certifying machine departure.', on_delete=django.db.models.deletion.PROTECT, related_name='dispatched_logs', to=settings.AUTH_USER_MODEL, verbose_name='Dispatch Officer')),
                ('equipment', models.ForeignKey(help_text='Equipment asset being dispatched or returned.', on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_returns', to='fleet.equipment', verbose_name='Equipment Asset')),
                ('return_officer', models.ForeignKey(blank=True, help_text='Workshop or receiving officer conducting check-in inspection.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_logs', to=settings.AUTH_USER_MODEL, verbose_name='Return Receiving Officer')),
                ('contract', models.ForeignKey(help_text='Contract governing this machine handover.', on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_returns', to='rentals.rentalcontract', verbose_name='Rental Contract')),
            ],
            options={
                'verbose_name': 'Dispatch & Return Log',
                'verbose_name_plural': 'Dispatch & Return Logs',
                'ordering': ['-dispatch_datetime'],
            },
        ),
    ]
