# Generated by Django 5.1.15 on 2026-10-08 08:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('rentals', '0003_quotation_rentalcontract_dispatchreturn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='rate_applied',
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='project_code',
            field=models.CharField(help_text='Unique project identifier (e.g., PRJ-001-01).', max_length=50, primary_key=True, serialize=False, verbose_name='Project Site Code'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', help_text='Operational status of this construction project site.', max_length=20, verbose_name='Site Status'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='grand_total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total quotation value including rental, transport, and taxes.', max_digits=12, verbose_name='Grand Total Amount (LKR)'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='rate_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', help_text='Default rate frequency tier (Daily, Weekly, Monthly).', max_length=20, verbose_name='Default Rate Type'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base rental charge before tax and transport (Sum of Line Items).', max_digits=12, verbose_name='Subtotal Amount (LKR)'),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='agreed_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final agreed rental rate per period.', max_digits=10, verbose_name='Agreed Rate (LKR)'),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='Primary machinery asset contracted for rental (or access all assets via contract items).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='fleet.equipment', verbose_name='Primary Equipment Asset'),
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('start_date', models.DateField(blank=True, help_text='Item-specific rental start date (defaults to quotation start date if empty).', null=True, verbose_name='Rental Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Item-specific rental completion date (defaults to quotation end date if empty).', null=True, verbose_name='Rental End Date')),
                ('rate_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', help_text='Rate frequency tier (Daily, Weekly, Monthly).', max_length=20, verbose_name='Rate Type')),
                ('rate_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Agreed unit rental rate for this equipment item.', max_digits=10, verbose_name='Applied Rate (LKR)')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated line item base tariff (Duration x Applied Rate).', max_digits=12, verbose_name='Line Subtotal (LKR)')),
                ('equipment', models.ForeignKey(help_text='Machinery asset requested for rental.', on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='fleet.equipment', verbose_name='Equipment Asset')),
                ('quotation', models.ForeignKey(help_text='Parent commercial quotation.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rentals.quotation', verbose_name='Quotation')),
            ],
            options={
                'verbose_name': 'Quotation Item',
                'verbose_name_plural': 'Quotation Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('start_date', models.DateField(help_text='Equipment rental start date.', verbose_name='Contract Start Date')),
                ('end_date', models.DateField(help_text='Equipment rental completion date.', verbose_name='Contract End Date')),
                ('rate_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Agreed unit rental rate.', max_digits=10, verbose_name='Agreed Rate (LKR)')),
                ('rate_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', help_text='Rate frequency tier.', max_length=20, verbose_name='Rate Type')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line item total amount.', max_digits=12, verbose_name='Line Subtotal (LKR)')),
                ('contract', models.ForeignKey(help_text='Parent rental contract.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rentals.rentalcontract', verbose_name='Rental Contract')),
                ('equipment', models.ForeignKey(help_text='Machinery asset contracted for rental.', on_delete=django.db.models.deletion.PROTECT, related_name='contract_items', to='fleet.equipment', verbose_name='Equipment Asset')),
            ],
            options={
                'verbose_name': 'Rental Contract Item',
                'verbose_name_plural': 'Rental Contract Items',
                'ordering': ['created_at'],
            },
        ),
    ]
