# Generated by Django 5.1.15 on 2026-10-05 08:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name of the equipment classification.', max_length=100, unique=True, verbose_name='Category Name')),
                ('code', models.SlugField(help_text='Short mnemonic code (e.g., EXC, GEN, CRN).', max_length=20, unique=True, verbose_name='Category Code')),
                ('description', models.TextField(blank=True, help_text='Detailed notes on equipment types included in this category.', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Equipment Category',
                'verbose_name_plural': 'Equipment Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('asset_code', models.CharField(help_text='Unique identifier (e.g., EQ-CAT-320-001).', max_length=50, primary_key=True, serialize=False, verbose_name='Asset Code')),
                ('equipment_name', models.CharField(help_text='Marketing or operational name of the machinery.', max_length=200, verbose_name='Equipment Name')),
                ('brand', models.CharField(help_text='Manufacturer brand (e.g., Caterpillar, Komatsu, JCB).', max_length=100, verbose_name='Brand / Manufacturer')),
                ('model_number', models.CharField(help_text='Manufacturer model designation (e.g., 320D, JS205).', max_length=100, verbose_name='Model Number')),
                ('serial_number', models.CharField(help_text='Chassis, engine, or manufacturer serial number.', max_length=100, unique=True, verbose_name='Serial / VIN Number')),
                ('manufacture_year', models.PositiveIntegerField(help_text='Calendar year machinery was manufactured.', verbose_name='Year of Manufacture')),
                ('purchase_cost', models.DecimalField(decimal_places=2, help_text='Original acquisition capital cost in Sri Lankan Rupees.', max_digits=12, verbose_name='Purchase Cost (LKR)')),
                ('purchase_date', models.DateField(help_text='Date the asset was acquired.', verbose_name='Purchase Date')),
                ('current_hour_meter', models.DecimalField(decimal_places=2, default=0.0, help_text='Latest cumulative operating hour meter reading.', max_digits=10, verbose_name='Current Hour Meter (hrs)')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('ON_RENT', 'On Rent'), ('MAINTENANCE', 'Maintenance'), ('BREAKDOWN', 'Breakdown'), ('INACTIVE', 'Inactive')], db_index=True, default='AVAILABLE', help_text='Current operational and reservation state of the asset.', max_length=20, verbose_name='Operational Status')),
                ('primary_image', models.ImageField(blank=True, help_text='High-resolution photo of the equipment.', null=True, upload_to='equipment/images/', verbose_name='Primary Asset Photo')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Structured key-value specifications (e.g., Operating Weight, Engine Power, Bucket Capacity).', verbose_name='Technical Specifications')),
                ('category', models.ForeignKey(help_text='Classification category for this machinery.', on_delete=django.db.models.deletion.PROTECT, related_name='equipment_list', to='fleet.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Equipment Asset',
                'verbose_name_plural': 'Equipment Fleet',
                'ordering': ['asset_code'],
            },
        ),
        migrations.CreateModel(
            name='RentalRate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Standard rental rate per hour (if applicable).', max_digits=10, null=True, verbose_name='Hourly Rate (LKR)')),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Standard rental rate per single 8-hour shift / day.', max_digits=10, verbose_name='Daily Rate (LKR)')),
                ('weekly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted package rate for a 7-day rental period.', max_digits=10, null=True, verbose_name='Weekly Rate (LKR)')),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted rate for long-term 30-day rental agreements.', max_digits=10, null=True, verbose_name='Monthly Rate (LKR)')),
                ('overtime_hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly penalty/charge for operating hours exceeding daily threshold.', max_digits=10, null=True, verbose_name='Overtime Rate (LKR/hr)')),
                ('minimum_rental_hours', models.PositiveIntegerField(default=8, help_text='Minimum billable operating hours per rental engagement.', verbose_name='Minimum Rental Hours')),
                ('effective_from', models.DateField(default=django.utils.timezone.now, help_text='Date from which this tariff becomes active.', verbose_name='Effective From Date')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this rate card is currently applicable.', verbose_name='Is Active Rate')),
                ('equipment', models.ForeignKey(help_text='Equipment asset this rate card applies to.', on_delete=django.db.models.deletion.PROTECT, related_name='rental_rates', to='fleet.equipment', verbose_name='Equipment Asset')),
            ],
            options={
                'verbose_name': 'Rental Rate Card',
                'verbose_name_plural': 'Rental Rate Cards',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
    ]
